import {frontendOrigin,apiOrigin,createOptions,getOptions,responseJSON} from './enroll.js';
import {memberText} from './member-copy.js';
const $=id=>document.getElementById(id),status=$('status'),inviteMode=location.pathname==='/invite.html';
const params=new URLSearchParams(location.search),sections=new Set(['home','timeline','albums','places','letters','search','manage-places']);
let language=params.get('lang')==='zh'?'zh':params.get('lang')==='en'?'en':navigator.language.toLowerCase().startsWith('zh')?'zh':'en';
let invitation=inviteMode?location.hash.slice(1):null;
if(inviteMode)history.replaceState(null,'',location.pathname+location.search);
let csrf=null,person=null,busy=false,pending=null,proof=null,popup=null,native=null,management=null,waiter=null,inviteValid=false,keys=[],inviteInfo=null,personRequest=null,dialogRender=null,notice={key:'checking',values:{},error:false};
const invitationLinks=new Map();let visibleLinkId=null,preparing=null;
const allowed=new Set(['me','credentials','management','people/add','transport/start','transport/confirm','login/options','login/verify','registration/options','registration/verify','invite/info','invite','invite-replace','invite-remove','invite-revoke','credential/rename','credential/revoke','logout']);
const t=(key,values={})=>memberText(language,key,values),date=value=>new Date(value).toLocaleString(language==='zh'?'zh-CN':'en-US',{dateStyle:'medium',timeStyle:'short'});
function say(key,values={},error=false){notice={key,values,error};status.textContent=key?t(key,values):'';status.classList.toggle('error',error);}
function applyLanguage(value){language=value==='zh'?'zh':'en';document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title='zkmzyx · '+t(inviteMode?'privateInvitation':'account');for(const e of document.querySelectorAll('[data-i18n]'))e.textContent=t(e.dataset.i18n);for(const e of document.querySelectorAll('[data-i18n-aria]'))e.setAttribute('aria-label',t(e.dataset.i18nAria));$('lang-zh').setAttribute('aria-pressed',String(language==='zh'));$('lang-en').setAttribute('aria-pressed',String(language==='en'));if(!$('label').value||['My passkey','我的通行密钥'].includes($('label').value))$('label').value=t('defaultPasskey');say(notice.key,notice.values,notice.error);if(pending)$('continue').textContent=t(pending.purpose==='login'?'signIn':'createPasskey');if(person&&!inviteMode)renderAccount();if(inviteInfo)renderInvite();dialogRender?.();}
async function api(action,body,method='POST'){
 if(!allowed.has(action))throw Error('denied');return send('/api/auth/'+action,body,method);
}
async function send(path,body,method='POST'){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{const r=await fetch(apiOrigin+path,{method,credentials:'include',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:controller.signal,headers:{...(method==='POST'?{'Content-Type':'application/json','X-Zkmzyx-Request':'1'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(method==='POST'?{body:JSON.stringify(body||{})}:{})});const value=await r.json();if(!r.ok){if(r.status===401)csrf=null;throw Object.assign(Error(value.error||'denied'),{status:r.status});}return value;}finally{clearTimeout(timer);}
}
function ceremonyView(){const stage=pending||preparing;const helper=document.querySelector('[data-i18n="secureStepHelp"]');if(helper)helper.hidden=!!stage;if(inviteMode){$('accept').hidden=!!stage;for(const e of document.querySelectorAll('[data-step]')){const n=Number(e.dataset.step),at=inviteValid?(pending?3:2):1;e.classList.toggle('done',n<at);e.classList.toggle('current',n===at);if(n===at)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');}}else{$('sign-in').hidden=stage?.purpose==='login';$('add').hidden=stage?.purpose==='add';}}
function clearPending(){pending=null;preparing=null;proof=null;native?.abort();native=null;$('continue').hidden=true;popup?.close();popup=null;ceremonyView();}
function buttons(){for(const b of document.querySelectorAll('button'))b.disabled=busy||b.dataset.protected==='true';if(inviteMode)$('accept').disabled=busy||!inviteValid;else $('invite').disabled=busy||!management?.people.length;}
async function run(fn){if(busy)return;busy=true;buttons();try{await fn();}catch(e){clearPending();if(!inviteMode&&['invitation_changed','invitation_not_removable'].includes(e.message)){hideLink();try{await refresh();}catch(refreshError){if(refreshError.status===401){signedOut();say('sessionEnded');return;}}}if(e.status===401&&!inviteMode){signedOut();say('sessionEnded');return;}const key=e.name==='NotAllowedError'?'cancelled':['partitioning_required','browser_check_timeout'].includes(e.message)?'partitionRequired':e.status===429?'tryLater':e.message==='final_credential_protected'?'keepFinalKey':e.message==='popup_blocked'?'allowPopup':['invalid_invitation','invalid_admission'].includes(e.message)?'inviteUnavailable':e.message==='invalid_account_identifier'?'validEmail':e.message==='invalid_person'?'validPerson':e.message==='person_request_conflict'?'requestConflict':e.message==='language_failed'?'languageFailed':e.message==='invitation_changed'?'invitationChanged':e.message==='invitation_not_removable'?'invitationNotRemovable':'unable';say(key,{},true);}finally{busy=false;buttons();}}
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function row(parent,title,detail){const r=node('div',undefined,'member-row'),heading=node('p',title,'member-row-title');r.append(heading);if(detail)r.append(node('p',detail,'quiet'));parent.append(r);return {r,heading};}
function badge(parent,key,state=''){parent.append(node('span',t(key),'member-badge '+state));}
function action(parent,key,fn,danger=false){const b=node('button',t(key),'button secondary'+(danger?' danger':''));b.type='button';b.addEventListener('click',()=>run(fn));parent.append(b);return b;}
function empty(parent,key){parent.append(node('p',t(key),'muted'));}
function dialog(titleKey,messageKey,values={},labelValue=null){return new Promise(resolve=>{
 const d=node('dialog',undefined,'member-dialog'),h=node('h2'),p=node('p'),actions=node('div',undefined,'member-actions'),yes=node('button',undefined,'button'),no=node('button',undefined,'button secondary');let input=null,done=false;
 if(labelValue!==null){input=node('input');input.maxLength=64;input.value=labelValue;input.autocomplete='off';input.setAttribute('aria-label',t('passkeyName'));}
 const finish=value=>{if(done)return;done=true;dialogRender=null;d.close();d.remove();resolve(value);};
 dialogRender=()=>{h.textContent=t(titleKey);p.textContent=t(messageKey,values);yes.textContent=t(input?'save':'confirm');no.textContent=t('cancel');input?.setAttribute('aria-label',t('passkeyName'));};dialogRender();
 yes.addEventListener('click',()=>finish(input?input.value:true));no.addEventListener('click',()=>finish(input?null:false));d.addEventListener('cancel',e=>{e.preventDefault();finish(input?null:false);});actions.append(no,yes);d.append(h,p);if(input)d.append(input);d.append(actions);document.body.append(d);d.showModal();(input||no).focus();
});}
function hideLink(){invitationLinks.clear();visibleLinkId=null;if($('handoff')){$('invite-link').value='';$('handoff').hidden=true;}if(person&&!inviteMode)renderAccount();}
function showLink(value){invitationLinks.clear();invitationLinks.set(value.id,frontendOrigin+value.link);visibleLinkId=value.id;renderAccount();$('invite-link').value=invitationLinks.get(value.id);$('handoff').hidden=false;}
async function copyLink(id){const link=invitationLinks.get(id);if(!link)throw Error('invitation_changed');try{await navigator.clipboard.writeText(link);say('linkCopied');}catch{$('invite-link').value=link;$('handoff').hidden=false;$('invite-link').focus();$('invite-link').select();say('copyManually');}}
function renderInvite(){$('invited-identity').textContent=inviteInfo.name+' · '+t(inviteInfo.role)+' · '+inviteInfo.accountIdentifier;}
function renderAccount(){
 $('identity').textContent=person.name+' · '+t(person.role)+' · '+person.email;
 $('keys').replaceChildren();const usable=keys.filter(k=>k.revoked_at===null);
 for(const k of usable){const {r,heading}=row($('keys'),k.label,t('added',{date:date(k.created_at)})+' · '+(k.last_used_at?t('lastUsed',{date:date(k.last_used_at)}):t('neverUsed')));if(k.backup_eligible)badge(heading,'syncCapable');const actions=node('div',undefined,'member-actions');r.append(actions);action(actions,'rename',async()=>{const label=await dialog('rename','renameHelp',{},k.label);if(label===null)return;await api('credential/rename',{id:k.id,label});await refresh();});const b=action(actions,'revoke',async()=>{if(!await dialog('revoke','revokeKeyHelp'))return;await api('credential/revoke',{id:k.id});signedOut();},true);if(usable.length===1){b.disabled=true;b.dataset.protected='true';b.title=t('keepFinalKey');r.append(node('p',t('finalKey'),'quiet'));}}
 const owner=person.role==='owner';$('people-section').hidden=!owner;$('invitations').hidden=!owner;if(!owner)return;
 $('people-list').replaceChildren();for(const p of management?.canonicalPeople||[]){const {r,heading}=row($('people-list'),p.name);badge(heading,p.role);badge(heading,p.account_status||'noAccount');if(p.role!=='owner'&&p.account_status===null)action(r,'invitePerson',async()=>{$('person').value=p.id;$('invitations').scrollIntoView({block:'start',behavior:'auto'});$('identifier').focus();});}
 const selected=$('person').value;$('person').replaceChildren();for(const p of management?.people||[]){const o=node('option',p.name+' · '+t(p.role));o.value=p.id;$('person').append(o);}if(management?.people.some(p=>p.id===selected))$('person').value=selected;
 $('invite').disabled=busy||!management?.people.length;$('person').disabled=!management?.people.length;$('identifier').disabled=!management?.people.length;
 $('invite-list').replaceChildren();if(!management?.people.length)empty($('invite-list'),'noEligiblePeople');if(!management?.invitations.length)empty($('invite-list'),'noInvitations');
 const invitations=management?.invitations||[],state=i=>i.consumed_at!==null?'accepted':i.revoked_at!==null?'revoked':i.expires_at<=Date.now()?'expired':'pending';
 for(const id of invitationLinks.keys())if(!invitations.some(i=>i.id===id&&state(i)==='pending'))invitationLinks.delete(id);
 let history=null;for(const group of ['pending','accepted','terminal'])for(const i of invitations.filter(i=>group==='terminal'?['revoked','expired'].includes(state(i)):state(i)===group)){
  const current=state(i),p=management.canonicalPeople.find(p=>p.id===i.person_id);let parent=$('invite-list');if(group==='terminal'){if(!history){history=node('details',undefined,'member-history');history.append(node('summary',t('invitationHistory')));parent.append(history);}parent=history;}
  const {r,heading}=row(parent,(p?.name||t('people'))+' · '+t(i.intent),group==='accepted'?t(p?.account_status||'accepted'):t('signInEmail')+': '+i.email+' · '+t('expires',{date:date(i.expires_at)}));badge(heading,current,current==='pending'?'pending':'');
  if(current==='pending'){if(invitationLinks.has(i.id))action(r,'copyInvitationLink',()=>copyLink(i.id));else action(r,'regenerateLink',async()=>{if(!await dialog('regenerateLink','regenerateHelp'))return;hideLink();const next=await api('invite-replace',{id:i.id});await refresh();showLink(next);say('invitationCreated');});action(r,'revokeInvitation',async()=>{if(!await dialog('revokeInvitation','revokeInviteHelp'))return;await api('invite-revoke',{id:i.id});hideLink();await refresh();},true);}
  else if(group==='terminal')action(r,'removeInvitation',async()=>{if(!await dialog('removeInvitation','removeInvitationHelp'))return;await api('invite-remove',{id:i.id});await refresh();say('invitationRemoved');},true);
 }
}
async function refresh(){const me=await api('me',null,'GET');csrf=me.csrf;person=me;if(inviteMode){invitation=null;location.replace('/');return;}$('welcome').hidden=true;$('account').hidden=false;keys=await api('credentials',null,'GET');management=me.role==='owner'?await api('management',null,'GET'):null;applyLanguage(me.language);say('');}
function signedOut(){csrf=null;person=null;management=null;keys=[];personRequest=null;hideLink();clearPending();$('account').hidden=true;$('welcome').hidden=false;$('keys').replaceChildren();$('invite-list').replaceChildren();$('people-list').replaceChildren();$('identity').textContent='';$('identifier').value='';$('person').replaceChildren();$('person-name').value='';$('add-person-fields').hidden=true;$('people-section').hidden=true;$('invitations').hidden=true;say('signedOut');}
function back(){const target=params.get('from'),fallback=sections.has(target)?'/#'+target:'/';try{const entries=window.navigation?.entries(),at=window.navigation?.currentEntry?.index,previous=entries?.find(e=>e.index===at-1),u=previous?.url?new URL(previous.url):null;if(u?.origin===frontendOrigin&&u.pathname==='/'){history.back();return;}}catch{}location.assign(fallback);}
window.addEventListener('message',event=>{if(event.origin===frontendOrigin&&event.source===popup&&event.data?.type==='zkmzyx-browser-check')waiter?.(event.data.ok===true);});
async function prepare(purpose){
 clearPending();popup=window.open('about:blank','_blank','popup,width=480,height=440');if(!popup)throw Error('popup_blocked');const opened=popup;let timer;
 preparing={purpose};ceremonyView();
 try{const t0=await api('transport/start');proof=t0.id;const checked=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('browser_check_timeout')),60000);waiter=ok=>ok?resolve():reject(Error('partitioning_required'));});opened.location.href=apiOrigin+'/api/auth/transport/top?id='+encodeURIComponent(proof)+'&return=product&lang='+language;say('browserCheck');await checked;await api('transport/confirm',{id:proof});const result=purpose==='login'?await api('login/options',{transportId:proof}):await api('registration/options',{purpose,...(purpose==='invite'?{token:invitation}:{}),transportId:proof});pending={...result,purpose};preparing=null;ceremonyView();$('continue').textContent=t(purpose==='login'?'signIn':'createPasskey');$('continue').hidden=false;say(purpose==='login'?'readySignIn':'readyCreate');}finally{clearTimeout(timer);waiter=null;opened.close();popup=null;}
}
async function complete(){const p=pending;if(!p)throw Error('denied');native=new AbortController();const c=await navigator.credentials[p.purpose==='login'?'get':'create']({publicKey:p.purpose==='login'?getOptions(p.options):createOptions(p.options),signal:native.signal});await api(p.purpose==='login'?'login/verify':'registration/verify',p.purpose==='login'?{id:p.id,response:responseJSON(c)}:{id:p.id,purpose:p.purpose,response:responseJSON(c),label:$('label').value});invitation=null;clearPending();if(p.purpose==='add'){await refresh();say('passkeyAdded');}else{await api('me',null,'GET');location.replace('/');}}
applyLanguage(language);$('back').addEventListener('click',e=>{e.preventDefault();back();});
for(const value of ['zh','en'])$('lang-'+value).addEventListener('click',()=>run(async()=>{if(person){try{await send('/api/journal',{action:'language',language:value});person.language=value;}catch{throw Error('language_failed');}}applyLanguage(value);const u=new URL(location.href);u.searchParams.set('lang',value);history.replaceState(null,'',u.pathname+u.search);}));
if(location.origin!==frontendOrigin||window.top!==window.self||!window.isSecureContext){invitation=null;say('secureSite',{},true);for(const b of document.querySelectorAll('button'))b.disabled=true;}
else{
 $('continue').addEventListener('click',()=>run(complete));
 if(inviteMode){run(async()=>{if(!/^[a-f0-9]{64}$/.test(invitation||''))throw Error('invalid_invitation');inviteInfo=await api('invite/info',{token:invitation});applyLanguage(inviteInfo.language);inviteValid=true;ceremonyView();$('accept').disabled=false;say('invitationReady');});$('accept').addEventListener('click',()=>run(()=>prepare('invite')));}
 else{
  $('sign-in').addEventListener('click',()=>run(()=>prepare('login')));$('add').addEventListener('click',()=>run(()=>prepare('add')));$('logout').addEventListener('click',()=>run(async()=>{await api('logout');signedOut();}));$('dismiss-link').addEventListener('click',hideLink);$('copy-link').addEventListener('click',()=>run(()=>copyLink(visibleLinkId)));
  $('show-add-person').addEventListener('click',()=>{$('add-person-fields').hidden=false;$('person-language').value=language;$('person-name').focus();});$('cancel-person').addEventListener('click',()=>{$('add-person-fields').hidden=true;});
  $('save-person').addEventListener('click',()=>run(async()=>{const name=$('person-name').value.trim(),preferred=$('person-language').value;if(!name||name.length>100)throw Error('invalid_person');if(!personRequest)personRequest={name,language:preferred,request_key:crypto.randomUUID().replaceAll('-','')};if(personRequest.name!==name||personRequest.language!==preferred)throw Error('person_request_conflict');await api('people/add',personRequest);personRequest=null;$('person-name').value='';$('add-person-fields').hidden=true;await refresh();say('personAdded');}));
  $('invite').addEventListener('click',()=>run(async()=>{hideLink();const p=management?.people.find(p=>p.id===$('person').value);if(!p)throw Error('denied');const identifier=$('identifier').value.trim().toLowerCase();if(!await dialog('createInvitation','inviteConfirm',{name:p.name,role:t(p.role),identifier}))return;const i=await api('invite',{person_id:p.id,account_identifier:identifier});await refresh();$('identifier').value='';showLink(i);say('invitationCreated');}));
  run(async()=>{try{await refresh();}catch(e){if(e.status!==401)throw e;signedOut();say('signInToOpen');}});
 }
}
window.addEventListener('pageshow',e=>{if(e.persisted&&!inviteMode)run(refresh);});
window.addEventListener('pagehide',()=>{invitation=null;inviteInfo=null;if(!inviteMode)signedOut();else{csrf=null;inviteValid=false;$('invited-identity').textContent='';hideLink();clearPending();}});
