import {frontendOrigin,apiOrigin,createOptions,getOptions,responseJSON} from './enroll.js';
const $=id=>document.getElementById(id),status=$('status'),inviteMode=location.pathname==='/invite.html';
let invitation=inviteMode?location.hash.slice(1):null;
if(inviteMode)history.replaceState(null,'',location.pathname);
let csrf=null,person=null,busy=false,pending=null,proof=null,popup=null,native=null,management=null,waiter=null,inviteValid=false;
const allowed=new Set(['me','credentials','management','transport/start','transport/confirm','login/options','login/verify','registration/options','registration/verify','invite/info','invite','invite-revoke','credential/rename','credential/revoke','logout']);
const say=s=>status.textContent=s;
async function api(action,body,method='POST'){
 if(!allowed.has(action))throw Error('denied');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{const r=await fetch(apiOrigin+'/api/auth/'+action,{method,credentials:'include',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:controller.signal,headers:{...(method==='POST'?{'Content-Type':'application/json','X-Zkmzyx-Request':'1'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(method==='POST'?{body:JSON.stringify(body||{})}:{})});const value=await r.json();if(!r.ok){if(r.status===401)csrf=null;throw Object.assign(Error(value.error||'denied'),{status:r.status});}return value;}finally{clearTimeout(timer);}
}
function clearPending(){pending=null;proof=null;native?.abort();native=null;$('continue').hidden=true;popup?.close();popup=null;}
function buttons(){for(const b of document.querySelectorAll('button'))b.disabled=busy;if(inviteMode)$('accept').disabled=busy||!inviteValid;}
async function run(fn){if(busy)return;busy=true;buttons();try{await fn();}catch(e){clearPending();if(e.status===401&&!inviteMode){signedOut();say('Your session has ended. Sign in with your passkey to continue. 登录已过期，请使用通行密钥继续。');return;}say(e.name==='NotAllowedError'?'Passkey confirmation was cancelled. Try again when ready. 通行密钥确认已取消，可重新尝试。':e.message==='partitioning_required'?'This browser must support private partitioned sessions with ordinary third-party cookies blocked. Check browser privacy settings, then try again. 请检查浏览器隐私设置。':e.status===429?'Please wait before trying again. 请稍后再试。':e.message==='final_credential_protected'?'Keep at least one usable passkey. 请至少保留一把可用通行密钥。':e.message==='popup_blocked'?'Allow the brief browser-check window for this site, then try again. 请允许本站弹出浏览器检查窗口。':e.message==='invalid_invitation'||e.message==='invalid_admission'?'This invitation is unavailable, expired or already used. Ask the Owner for a new invitation. 邀请不可用、已过期或已使用，请联系所有者。':e.message==='invalid_account_identifier'?'Enter a valid private sign-in email. 请输入有效的私人登录邮箱。':'Unable to complete. Try signing in if confirmation may have finished; otherwise try again or contact the Owner. 如确认可能已完成，请先尝试登录；否则重试或联系所有者。');}finally{busy=false;buttons();}}
function textRow(parent,title,detail){const row=document.createElement('div');row.className='row';const p=document.createElement('p');p.textContent=title;row.append(p);const small=document.createElement('p');small.className='quiet';small.textContent=detail;row.append(small);parent.append(row);return row;}
function confirmAction(message){return new Promise(resolve=>{const dialog=document.createElement('dialog'),p=document.createElement('p'),yes=document.createElement('button'),no=document.createElement('button');p.textContent=message;yes.textContent='Confirm · 确认';no.textContent='Cancel · 取消';no.className='secondary';let done=false;const finish=value=>{if(done)return;done=true;dialog.close();dialog.remove();resolve(value);};yes.addEventListener('click',()=>finish(true));no.addEventListener('click',()=>finish(false));dialog.addEventListener('cancel',event=>{event.preventDefault();finish(false);});dialog.append(p,yes,no);document.body.append(dialog);dialog.showModal();no.focus();});}
function button(row,text,fn){const b=document.createElement('button');b.className='secondary';b.textContent=text;b.addEventListener('click',()=>run(fn));row.append(b);}
async function refresh(){const me=await api('me',null,'GET');csrf=me.csrf;person=me;if(inviteMode){invitation=null;location.replace('/');return;}$('welcome').hidden=true;$('account').hidden=false;$('identity').textContent=me.name+' · '+({owner:'Owner · 所有者',partner:'Partner · 伴侣',viewer:'Viewer · 访客'}[me.role]||'')+' · '+me.email;
 const keys=await api('credentials',null,'GET');$('keys').replaceChildren();const usable=keys.filter(k=>k.revoked_at===null);for(const k of usable){const row=textRow($('keys'),k.label,k.last_used_at?'Last used · 最近使用 '+new Date(k.last_used_at).toLocaleDateString():'Not used for sign-in yet · 尚未用于登录');button(row,'Rename · 重命名',async()=>{const label=prompt('Passkey name · 通行密钥名称',k.label);if(label===null)return;await api('credential/rename',{id:k.id,label});await refresh();});if(usable.length>1)button(row,'Revoke · 撤销',async()=>{if(!await confirmAction('Revoke this passkey and sign out all sessions? 撤销此通行密钥并退出所有登录？'))return;await api('credential/revoke',{id:k.id});signedOut();});}
 $('invitations').hidden=me.role!=='owner';if(me.role==='owner'){management=await api('management',null,'GET');$('person').replaceChildren();for(const p of management.people){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+(p.role==='partner'?'Partner · 伴侣':'Viewer · 访客');$('person').append(o);}$('invite-list').replaceChildren();for(const i of management.invitations){const state=i.consumed_at!==null?'Accepted · 已接受':i.revoked_at!==null?'Revoked · 已撤销':i.expires_at<=Date.now()?'Expired · 已过期':'Pending · 待接受';const p=management.people.find(p=>p.id===i.person_id)||management.accounts.find(p=>p.person_id===i.person_id);const row=textRow($('invite-list'),(p?.name||'Private member')+' · '+i.intent+' · '+state,'Sign-in email · 登录邮箱 '+i.email+' · '+new Date(i.expires_at).toLocaleString());if(i.consumed_at===null&&i.revoked_at===null&&i.expires_at>Date.now())button(row,'Revoke invitation · 撤销邀请',async()=>{if(!await confirmAction('Revoke this pending invitation? 撤销此待接受邀请？'))return;await api('invite-revoke',{id:i.id});hideLink();await refresh();});}}
 say('');}
function hideLink(){if($('handoff')){$('invite-link').value='';$('handoff').hidden=true;}}
function signedOut(){csrf=null;person=null;management=null;hideLink();clearPending();$('account').hidden=true;$('welcome').hidden=false;$('keys').replaceChildren();$('invite-list').replaceChildren();$('identity').textContent='';$('identifier').value='';say('Signed out. Use your passkey to return. 已退出，请使用通行密钥重新登录。');}
window.addEventListener('message',event=>{if(event.origin===frontendOrigin&&event.source===popup&&event.data?.type==='zkmzyx-browser-check')waiter?.();});
async function prepare(purpose){
 clearPending();popup=window.open('about:blank','_blank','popup,width=480,height=440');if(!popup)throw Error('popup_blocked');
 const opened=popup;let timer;try{const t=await api('transport/start');proof=t.id;const checked=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('browser_check_timeout')),60000);waiter=resolve;});opened.location.href=apiOrigin+'/api/auth/transport/top?id='+encodeURIComponent(proof)+'&return=product';say('Complete the brief browser check, then return here. 完成浏览器检查后返回此页。');await checked;await api('transport/confirm',{id:proof});const result=purpose==='login'?await api('login/options',{transportId:proof}):await api('registration/options',{purpose,...(purpose==='invite'?{token:invitation}:{}),transportId:proof});pending={...result,purpose};$('continue').textContent=purpose==='login'?'Sign in with Passkey · 通行密钥登录':'Create Passkey · 创建通行密钥';$('continue').hidden=false;say(purpose==='login'?'Ready. Confirm your passkey to sign in. 已就绪，请确认通行密钥以登录。':'Ready. Confirm on your device to create your passkey. 已就绪，请在设备上确认创建通行密钥。');}finally{clearTimeout(timer);waiter=null;opened.close();popup=null;}
}
async function complete(){const p=pending;if(!p)throw Error('denied');native=new AbortController();const c=await navigator.credentials[p.purpose==='login'?'get':'create']({publicKey:p.purpose==='login'?getOptions(p.options):createOptions(p.options),signal:native.signal});await api(p.purpose==='login'?'login/verify':'registration/verify',p.purpose==='login'?{id:p.id,response:responseJSON(c)}:{id:p.id,purpose:p.purpose,response:responseJSON(c),label:$('label').value});invitation=null;clearPending();if(p.purpose==='add'){await refresh();say('Passkey added. 通行密钥已添加。');}else{await api('me',null,'GET');location.replace('/');}}
if(location.origin!==frontendOrigin||window.top!==window.self||!window.isSecureContext){invitation=null;say('Open the exact secure zkmzyx site in a top-level tab. 请在安全的 zkmzyx 网站标签页中打开。');for(const b of document.querySelectorAll('button'))b.disabled=true;}else{
 $('continue').addEventListener('click',()=>run(complete));
 if(inviteMode){run(async()=>{if(!/^[a-f0-9]{64}$/.test(invitation||''))throw Error('invalid_invitation');const i=await api('invite/info',{token:invitation});$('invited-identity').textContent=i.name+' · '+i.role+' · '+i.accountIdentifier;inviteValid=true;$('accept').disabled=false;say('Your private invitation is ready. 私人邀请已就绪。');});$('accept').addEventListener('click',()=>run(()=>prepare('invite')));}
 else{$('sign-in').addEventListener('click',()=>run(()=>prepare('login')));$('add').addEventListener('click',()=>run(()=>prepare('add')));$('logout').addEventListener('click',()=>run(async()=>{await api('logout');signedOut();}));$('dismiss-link').addEventListener('click',hideLink);$('invite').addEventListener('click',()=>run(async()=>{hideLink();const p=management?.people.find(p=>p.id===$('person').value);if(!p)throw Error('denied');const identifier=$('identifier').value.trim().toLowerCase();if(!await confirmAction('Invite '+p.name+' as '+p.role+' using this separate sign-in email?\n'+identifier))return;const i=await api('invite',{person_id:p.id,account_identifier:identifier});await refresh();$('identifier').value='';$('invite-link').value=frontendOrigin+i.link;$('handoff').hidden=false;say('Invitation created. Share the private link with the intended person. 邀请已创建，请将私人链接交给指定成员。');}));run(async()=>{try{await refresh();}catch(e){if(e.status!==401)throw e;signedOut();say('Sign in to open your private journal. 登录以打开私人日记。');}});}
}
window.addEventListener('pagehide',()=>{invitation=null;csrf=null;person=null;management=null;hideLink();clearPending();});
